<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">

    <title>TicTacToe</title>
    <link rel="stylesheet" href="http://getbootstrap.com/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="css/style.css">
</head>

<body>
    <div id="game">

        <div class="header">
            <h3>Tic Tac Toe</h3>
        </div>

        <?php if ($winner !== null) : ?>

            <div class="current-player alert alert-success">
                <p><strong><?php echo $winner->getName() ?></strong> won the game!</p>
            </div>

            <?php require_once 'includes/board-renderer.phtml' ?>

        <?php elseif ($draw) : ?>

            <div class="current-player alert alert-danger">
                <p><strong>It&#39;s a draw!</strong> Nobody won the game =[</p>
            </div>

        <?php else : ?>

        <div class="current-player alert alert-info">
            <p><strong><?php echo $game->getCurrentPlayer()->getName() ?></strong> is playing</p>
        </div>

        <?php require_once 'includes/board-renderer.phtml' ?>

        <?php endif; ?>

        <form method="post">
            <input type="submit" name="restart" value="Restart" class="btn btn-danger" />
        </form>
    </div>

</body>
</html>